kind: Service
apiVersion: v1
metadata:
  name: train-schedule-svc
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: train-schedule-ingress
spec:
  rules:
  - host: trainschedulesvc.ingress.eecluster.cpet.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - backend:
          serviceName: train-schedule-svc
          servicePort: 80
    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      hostnetwork: true
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
